networks:
  default:
    external: true
    name: modnet
services:
  mod:
    container_name: mod
    deploy: {}
    entrypoint: bash -c "m serve port=50133 key=server remote=0 mod=mod"
    environment: []
    image: mod:latest
    ports:
    - 50133:50133
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    working_dir: /root/mod
