networks:
  host:
    external: true
services:
  mod:
    container_name: mod
    deploy: {}
    entrypoint: bash -c "m serve port=50079 key=mod remote=0 mod=mod"
    environment: []
    image: mod:latest
    ports:
    - 50079:50079
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod/server:/root/.mod/server
    - ~/.mod/key/mod:/root/.mod/key/mod
    - ~/.mod/mod:/root/.mod/mod
    working_dir: /root/mod
