networks:
  default:
    external: true
    name: modnet
services:
  mod:
    container_name: mod
    deploy: {}
    entrypoint: bash -c "m serve port=50144 key=mod remote=0 mod=mod"
    image: mod:latest
    ports:
    - 50144:50144
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/core/chain:/root/mod/mod/core/chain
    working_dir: /root/mod/mod/core/chain
version: '3.8'
