services:
  mod:
    container_name: mod
    deploy: {}
    entrypoint: bash -c "m serve port=50100 key=mod remote=0 mod=mod"
    image: mod:latest
    ports:
    - 50100:50100
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod/server:/root/.mod/server
    - ~/.mod/key/mod:/root/.mod/key/mod
    - ~/.mod/mod:/root/.mod/mod
    - ~/mod/mod/modules/dev/dev/tool/_misc/summod:/root/mod/mod/modules/dev/dev/tool/_misc/summod
    working_dir: /root/mod/mod/modules/dev/dev/tool/_misc/summod
version: '3.8'
