networks:
  default:
    external: true
    name: modnet
services:
  app:
    build:
      context: ./
    container_name: app
    deploy: {}
    entrypoint: bash -c "npm run build && npm run start"
    environment:
    - NEXT_PUBLIC_API_URL=http://0.0.0.0:8000
    image: app:latest
    ports:
    - 3000:3000
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod/mod/modules/app:/app
    - /app/node_modules
    - ~/.mod:/root/.mod
    - ~/mod:/root/mod
    - /app/.next
    working_dir: /app
  mod:
    container_name: mod
    deploy: {}
    entrypoint: bash -c "m serve port=50067 key=server remote=0 mod=mod"
    image: mod
    ports:
    - 50067:50067
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/modules/app:/root/mod/mod/modules/app
    working_dir: /root/mod/mod/modules/app
version: '3.8'
