networks:
  default:
    external: true
    name: modnet
services:
  app:
    build:
      context: ./
    container_name: app
    deploy: {}
    entrypoint: bash -c "npm run dev"
    environment:
    - NEXT_PUBLIC_API_URL=http://0.0.0.0:8000
    image: app:latest
    ports:
    - 3001:3000
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ./:/app
    - /app/node_modules
    - /app/.next
    working_dir: /app
version: '3.8'
