networks:
  default:
    external: true
    name: modnet
services:
  bt:
    container_name: bt
    deploy: {}
    entrypoint: bash -c "m serve port=50085 key=bt remote=0 mod=bt"
    image: bt
    ports:
    - 50085:50085
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/_mods/bt:/root/mod/mod/_mods/bt
    working_dir: /root/mod/mod/_mods/bt
version: '3.8'
