networks:
  default:
    external: true
    name: modnet
services:
  dev:
    container_name: dev
    deploy: {}
    entrypoint: bash -c "m serve port=50099 key=dev remote=0 mod=dev"
    image: mod:latest
    ports:
    - 50099:50099
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/modules/dev:/root/mod/mod/modules/dev
    working_dir: /root/mod/mod/modules/dev
version: '3.8'
